# Generated by Django 4.2.28 on 2026-02-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='required_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='reward_points',
            field=models.IntegerField(default=100),
        ),
    ]
